[package]
name = "pac-window"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
winit.workspace = true
wgpu.workspace = true
glam.workspace = true
pac-math = { path = "../pac-math" }

[features]
default = []
