[package]
name = "pac-math"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
glam.workspace = true
bytemuck.workspace = true
serde = { workspace = true, optional = true }

[features]
default = []
serde = ["dep:serde", "glam/serde"]
